name: ki_fuel
description: "Ki Fuel - Kirkuk Fuel Quota Tracker"
publish_to: "none"

version: 2.0.3

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State management
  provider: ^6.1.1

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Local notifications
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0

  # Date formatting
  intl: 0.20.2

  http: ^1.2.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  url_launcher: ^6.2.0
  geolocator: ^13.0.2

  # App info
  package_info_plus: ^8.0.0
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  firebase_analytics: ^12.0.4
  firebase_crashlytics: ^5.0.5
  cloud_firestore: ^6.1.0
  firebase_remote_config: ^6.1.2
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

# إعدادات أيقونة التطبيق
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assests/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assests/logo.png"

# إعدادات سبلاش أندرويد
flutter_native_splash:
  color: "#FFFFFF"
  fullscreen: false
  android_12:
    color: "#FFFFFF"
    fullscreen: false

flutter:
  uses-material-design: true

  assets:
    - assests/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
